apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: financial-sentiment-hpa
  namespace: financial-sentiment-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: financial-sentiment-ui
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
