name: Build and Push to ECR

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'    # Only trigger on changes to this folder
      - '.github/workflows/**'        # Optional: include workflow file changes
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: financial-sentiment-app
  AWS_ROLE_ARN: "arn:aws:iam::507992857438:role/github-actions-role"
  DEPLOYMENT_FILE: eks/deployment.yml

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_abencomoc
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          context: .
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      # Set the full image URI as output
      - name: Set image URI
        id: image-uri
        run: |
          echo "image_uri=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}" >> $GITHUB_OUTPUT

  # update-deployment:
  #   needs: build-and-push
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
        
  #     - name: Update deployment.yaml
  #       uses: fjogeleit/yaml-update-action@main
  #       with:
  #         valueFile: ${{ env.ECR_REPOSITORY }}
  #         propertyPath: 'spec.template.spec.containers[0].image'  # Adjust path to your YAML structure
  #         value: ${{ needs.build.outputs.image_uri }}
  #         commitChange: true
  #         branch: main
  #         token: ${{ secrets.GITHUB_TOKEN }}
